### ISSUE TITLE
Uitzoeken hoe de opendagen in elkaar zitten.

### ISSUE THREAD

**Issue by donfokker** [DoniBoye/Project_Week_1#5]

**Comment by IISuperboggie** [comment]
[Open dagen.docx](https://github.com/DoniBoye/Project_Week_1/files/5445535/Open.dagen.docx)

**Comment by IISuperboggie** [comment]
[Open dagen.docx](https://github.com/DoniBoye/Project_Week_1/files/5445683/Open.dagen.docx)
