### ISSUE TITLE
Uitzoeken wat de school regels zijn. (Muhannad)

### ISSUE THREAD

**Issue by donfokker** [DoniBoye/Project_Week_1#6]

**Comment by mootje20** [comment]
****School regels****

Wat zijn de school regels?
De school regels van de opleiding software developer zijn behoorlijk veel regels, hieronder zal ik de belangrijkste regels noemen:

1- ROC Nijmegen pas:
-	Elke student op het ROC Nijmegen is verplicht om een student pas te kunnen aantonen
2- Mondkapje:
-	De mondkapjes worden in het hele onderwijs verplicht als het straks wettelijk goed is geregeld. Het is nog niet duidelijk op welke datum het zover is.
3- Verzuim:
-	De school is verplicht om ongeoorloofd verzuim te melden bij DUO Als de student 16 klokuren (22 lesuren) ongeoorloofd afwezig is in 4 weken of zich zeer regelmatig ziek meldt.
-	Voor meer informatie: 
https://www.roc-nijmegen.nl/organisatie/verzuim
4- Sport op maat (SOP):   
-	Elke student van de opleiding software developer   is verplicht om het programma van sport op maat te volgen en die sporten kies je zelf!
-	Voor meer informatie:
https://www.roc-nijmegen.nl/organisatie/sport-op-maat
5- Kantines:
-	De kantines blijven gesloten voor studenten.
6- info:
Voor meer info over school regels:
-	https://www.roc-nijmegen.nl/organisatie/rechten-en-plichten
