### ISSUE TITLE
Uitzoeken hoe de toetsen werken van elk vak. (Muhannad)

### ISSUE THREAD

**Issue by donfokker** [DoniBoye/Project_Week_1#7]

**Comment by mootje20** [comment]
Toetsen 

Hoe werk de toetsen van elke vak?

1-	Nederlands:
Online Toetsen bij NU Nederlands (online)
2-	Engels:
Online Toetsen bij My English Lab
3-	Rekenen:
Digitaal op de site van Studiemeter (met licentie). Ieder periodecijfer is het cijfer van de domeintoets van die periode.

4-	Programmering:
-	HTML
Project maken
-	CSS
Project maken
-	JAVA:
	Je cijfer bestaat voor 80% uit het maken van een eindopdracht en het 	inleveren van het eindproject. De andere 20% bestaat uit het maken van de 6 	Quizzes over de vocabulary van Java.
-	PYHTHON:
Project maken
5-	Scrum:
	Summatieve toets?
6-	Computational Thinking:
	Instructie, zelfstudie, groepsactiviteiten, projectmatig samenwerken, 	zelfstandig werken
7-	IT Essentials:
Online toetsen bij Networking Academy
8-	Networking Essentials:
	Online toetsen bij Networking Academy	
9-	L&B
	Eindtoets/portfolio opdracht per dimensie
